train:
  id: robocasa
  size: [256, 256]
num_actions: 12
path_data_low_res: /n/holylabs/ydu_lab/Lab/zhangxiangcheng/code/diamond/dataset/robocasa/mg_im # TO DEFINE
path_data_full_res: null # TO DEFINE
keymap: csgo
